"""Public Core surface for the admitted workspace foundation."""

from .artifacts import ArtifactContent, ArtifactError, ArtifactInspection
from .context import ContextPackage, open_work
from .handoffs import MAX_HANDOFF_BYTES, AcceptedHandoff, handoff_request
from .mutations import (
    AuthorizationPrompt,
    LocalAuthorization,
    MutationError,
    ProjectionRebuildError,
    apply_mutation,
    authorize_local,
    inspect_artifacts,
    prepare_authorization,
    read_artifact,
    read_handoffs,
    read_history,
    read_projection_status,
    read_receipt,
    read_records,
    rebuild_projections,
)
from .projections import ProjectionStatus
from .protocol import (
    ArtifactReference,
    ArtifactVersion,
    ContextQuery,
    Handoff,
    HandoffDelivery,
    MutationEvent,
    MutationHistory,
    MutationReceipt,
    MutationRequest,
    ReceiptQuery,
)
from .records import (
    Artifact,
    Event,
    InitialRecords,
    Process,
    RecordsSnapshot,
    Work,
    create_initial_records,
)
from .workspace import (
    WorkspaceError,
    WorkspaceInfo,
    init_workspace,
    migrate_workspace,
    read_workspace,
)

__all__ = [
    "ContextPackage",
    "ContextQuery",
    "open_work",
    "AcceptedHandoff",
    "Handoff",
    "HandoffDelivery",
    "MAX_HANDOFF_BYTES",
    "handoff_request",
    "read_handoffs",
    "ArtifactContent",
    "ArtifactError",
    "ArtifactInspection",
    "ArtifactReference",
    "ArtifactVersion",
    "ProjectionRebuildError",
    "ProjectionStatus",
    "read_artifact",
    "inspect_artifacts",
    "read_projection_status",
    "rebuild_projections",
    "AuthorizationPrompt",
    "LocalAuthorization",
    "MutationError",
    "MutationEvent",
    "MutationHistory",
    "MutationReceipt",
    "MutationRequest",
    "ReceiptQuery",
    "apply_mutation",
    "authorize_local",
    "prepare_authorization",
    "read_history",
    "read_receipt",
    "Artifact",
    "Event",
    "InitialRecords",
    "Process",
    "RecordsSnapshot",
    "Work",
    "WorkspaceError",
    "WorkspaceInfo",
    "create_initial_records",
    "init_workspace",
    "migrate_workspace",
    "read_records",
    "read_workspace",
]
